# fly.toml app configuration file generated for familycody on 2024-09-10T23:45:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'familycody'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.21.4'

[env]
  PORT = '8888'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
